#!/usr/bin/env perl

use List::Util max;
use Getopt::Std;

my %opts;
my @columns;
my %colset;

getopts('hd:',\%opts);

my $INDEL="\t";
my $OUTDEL="\t";
$INDEL = $opts{'d'} if exists $opts{'d'};

my $n = 0;
foreach $file (@ARGV) {
	open(FH,'<',$file);
	while (<FH>) {
		chomp;
		if($. == 1) {
			@cols = split /[$INDEL]/, $_;
			my %cols;
			map {$cols{$_}++} @cols;
			$columns[$n] = \%cols;
			map {$colset{$_}++} @cols;			
			$n++;
		} else {
			last
		}
	}
	close(FH);
}

my $max_length = max(map {length($_)} keys %colset);

foreach $name (sort keys %colset) {
	$pad = " " x ($max_length - length($name) + 1);
	print $name . $pad;
	foreach my $f (0..$#columns) { exists $columns[$f]->{$name} ? print 'x' : print '-'}
	print "\n";
}
