#!/usr/bin/env bash

function usage () {
	cat - <<-EOM
	usage: $(basename $0) [-h] ID
	
	Stop running instance

	parameters:
	  -h    Show this help message
	  ID    Instance ID
	EOM
	exit 0
}

function main() {
	aws ec2 stop-instances --instance-ids $1
}

while getopts 'h' opt; do
	case "$opt" in
		h) usage
		   ;;
		*) exit 1
		   ;;
	esac
done

[[ $# != 1 ]] && usage

main
