#!/usr/bin/env bash

function usage() {
	cat - <<-EOM
	usage: $(basename $0) [-h] REPO

	List repository colaborators

	paramters
	  -h    Show this help message
	  REPO  Repository
	EOM
	exit 1
}

function main() {
	curl -s -X GET -u $GITHUB_USER:$GITHUB_TOKEN "https://api.github.com/repos/$GITHUB_USER/$1/collaborators" | \
		jq -r '.[] | .login + ": " + .role_name'
}

while getopts 'h' opt; do
	case "$opt" in
		h) usage
		   ;;
		*) exit 1
		   ;;
	esac
done
shift $((OPTIND-1))

[[ $# != 1 ]] && usage

main $1
