#!/usr/bin/env bash

function usage() {
	cat - <<-EOM
	usage: $(basename $0) [-h]

	List Github users

	paramters
	  -h    Show this help message
	EOM
	exit 1
}

function main() {
	curl -s "https://api.github.com/orgs/rs21io/members" \
		-H "Accept: application/vnd.github.v3+json" \
		-H "Authorization: token $GITHUB_TOKEN" | \
		jq -r '.[].login'
}

while getopts 'h' opt; do
	case "$opt" in
		h) usage
		   ;;
		*) exit 1
		   ;;
	esac
done

[[ $# != 0 ]] && usage

main
